### ISSUE TITLE
Test suite failing with latest GAP changes

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/hap#99]
The HAP test suite is experiencing new failures with the latest GAP master. See https://github.com/gap-system/gap/issues/5247 . There were two relevant changes made to GAP in the time in which the breakage started (details in the aforementioned issue). One changes the order of `AsList(G)` where `G` is a perm group. The other changes some aspects how fp groups are handled.

The `hap` failure looks like this:
```
########> Diff in /home/runner/gap/pkg/hap-1.47//tst/testallV11/nonabelian.tst:16
# Input is:
Set(List(StemGroups(G),IdGroup));
# Expected output:
[ [ 32, 28 ], [ 64, 73 ] ]
# But found:
[ [ 32, 27 ], [ 64, 73 ] ]
########
```

My guess is that the result of `StemGroups` is only defined up to isoclinism, and due to changes in the fp group code, now a different representative is picked.

This suggest that the test should be improved to accept any valid output, not just a single specific one. E.g one could check that the output consists of two groups; one with id `[ 64, 73 ]` and the other with id in the set `[ [ 32, 27 ], [ 32, 28 ], [ 32, 34 ] ]`

**Comment by grahamknockillaree** [comment]
Hi Max,

Thanks.

I'll sort these issues out the week after next when my teaching/examining  ends.

All the best,
Graham


School of Mathematical & Statistical Sciences
National University of Ireland, Galway
tel: 091 493011
________________________________
From: Max Horn ***@***.***>
Sent: Wednesday, December 7, 2022 7:38 AM
To: gap-packages/hap ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gap-packages/hap] Test suite failing with latest GAP changes (Issue #99)

EXTERNAL EMAIL: This email originated outside the University of Galway. Do not open attachments or click on links unless you believe the content is safe.
RÍOMHPHOST SEACHTRACH: Níor tháinig an ríomhphost seo ó Ollscoil na Gaillimhe. Ná hoscail ceangaltáin agus ná cliceáil ar naisc mura gcreideann tú go bhfuil an t-ábhar sábháilte.


The HAP test suite is experiencing new failures with the latest GAP master. See gap-system/gap#5247<https://github.com/gap-system/gap/issues/5247> . There were two relevant changes made to GAP in the time in which the breakage started (details in the aforementioned issue). One changes the order of AsList(G) where G is a perm group. The other changes some aspects how fp groups are handled.

The hap failure looks like this:

########> Diff in /home/runner/gap/pkg/hap-1.47//tst/testallV11/nonabelian.tst:16
# Input is:
Set(List(StemGroups(G),IdGroup));
# Expected output:
[ [ 32, 28 ], [ 64, 73 ] ]
# But found:
[ [ 32, 27 ], [ 64, 73 ] ]
########


My guess is that the result of StemGroups is only defined up to isoclinism, and due to changes in the fp group code, now a different representative is picked.

This suggest that the test should be improved to accept any valid output, not just a single specific one. E.g one could check that the output consists of two groups; one with id [ 64, 73 ] and the other with id in the set [ [ 32, 27 ], [ 32, 28 ], [ 32, 34 ] ]

**Comment by grahamknockillaree** [comment]
I think I've now fixed this issue.

**Comment by fingolfin** [comment]
Are you sure? The CI tests on this very repository still fail with the same error when run against GAP master. See https://github.com/gap-packages/hap/actions/runs/3767994701/jobs/6406057391

**Comment by grahamknockillaree** [comment]
Seems to be fixed now. I had accidentally copied the fixed file to the wrong folder, leaving the old file as part of the test.  Thanks!

**Comment by fingolfin** [comment]
@grahamknockillaree since things seem to working now, it would be great to get a new HAP release so that the package distro test suite passes again :-).

**Comment by grahamknockillaree** [comment]
I'll do this tomorrow.

**Comment by fingolfin** [comment]
Thank you, @grahamknockillaree
